# Generated by Django 3.0 on 2020-09-07 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200907_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
